name: GitVersion

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: gitversion-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "6.0.x"

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Publish version summary
        run: |
          {
            echo "## GitVersion"
            echo "- SemVer: \`${{ steps.gitversion.outputs.semVer }}\`"
            echo "- FullSemVer: \`${{ steps.gitversion.outputs.fullSemVer }}\`"
            echo "- InformationalVersion: \`${{ steps.gitversion.outputs.informationalVersion }}\`"
            echo "- BranchName: \`${{ steps.gitversion.outputs.branchName }}\`"
            echo "- Sha: \`${{ steps.gitversion.outputs.sha }}\`"
          } >> "$GITHUB_STEP_SUMMARY"

