name: PR Branch Guard

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  validate-source-target:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR branch routing policy
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          set -euo pipefail

          echo "base=$BASE_REF head=$HEAD_REF"

          if [[ "$BASE_REF" == "main" ]]; then
            if [[ "$HEAD_REF" != "develop" ]]; then
              echo "ERROR: PRs into main are only allowed from develop."
              exit 1
            fi
            exit 0
          fi

          if [[ "$BASE_REF" == "develop" ]]; then
            if [[ "$HEAD_REF" =~ ^(feature|feat|fix|refactor|perf|chore|docs|style|test|build|ci|hotfix|release)/.+$ ]]; then
              exit 0
            fi
            echo "ERROR: PRs into develop must use a conventional prefix (feat/, fix/, refactor/, perf/, chore/, docs/, style/, test/, build/, ci/, hotfix/, release/)."
            exit 1
          fi

          echo "ERROR: PR target branch '$BASE_REF' is not allowed by policy."
          exit 1

