name: Release PR auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  merge-release-pr:
    if: >
      !github.event.pull_request.draft &&
      startsWith(github.head_ref, 'release-please--')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Auto-approve release PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          gh pr review "$PR_NUMBER" --repo "$REPO" --approve --body "Auto-approve release-please PR."

      - name: Wait for required checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          gh pr checks "$PR_NUMBER" --repo "$REPO" --required --watch

      - name: Merge release PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail
          gh pr merge "$PR_NUMBER" --repo "$REPO" --squash --delete-branch
