name: Bug report
description: Report a reproducible defect
title: "[bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps so maintainers can reproduce the issue
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag, branch, or commit SHA
  - type: textarea
    id: logs
    attributes:
      label: Logs or stack trace
      render: shell
  - type: textarea
    id: regression
    attributes:
      label: Regression test
      description: |
        Should this fix be guarded by a regression test? If yes, describe the
        assertion and a diagnostic hint to display when it fails.
        See: memories/patterns/regression-test-patterns.md
      placeholder: |
        Assertion: "Script must NOT use ping for VIP detection"
        Hint: "MetalLB VIPs filter ICMP -- use curl --connect-timeout instead"
        Lesson: MetalLB VIPs do not respond to ICMP ping
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched for existing issues.
          required: true
        - label: I removed secrets and private data from logs.
          required: true
        - label: I considered whether a regression test should guard this fix.
